apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest
  labels:
    app: elasticsearch
    role: ingest
spec:
  selector:
    matchLabels:
      app: elasticsearch
      role: ingest
  serviceName: data-headless
  replicas: 3
  template:
    metadata:
      labels:
        app: elasticsearch
        role: ingest
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: es-data
        image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
        # resources:
        #   limits:
        #     cpu: "800m"
        #   requests:
        #     cpu: "500m"
        securityContext:
          privileged: true
        env:
        - name: cluster.name
          value: "my-es-cluster"
        - name: node.data
          value: "false"
        - name: node.master
          value: "false"
        - name: node.ingest
          value: "true"
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ES_PATH_CONF
          value: "/usr/share/elasticsearch/config"
        - name: network.host
          value: "_site_"
        - name: discovery.seed_hosts
          value: master-headless
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        - name: path.data
          value: "/data/data/"
        - name: path.logs
          value: "/data/log"
        ports:
        - containerPort: 9200
          name: external
        - containerPort: 9300
          name: internal2
        volumeMounts:
        - name: storage
          mountPath: /data
      