apiVersion: v1
kind: Service
metadata:
  name: master-headless
  labels:
    app: elasticsearch
    role: master
spec:
  selector:
    app: elasticsearch
    role: master
  ports:
  - port: 9300
    name: internal
    protocol: TCP
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: master
  labels:
    app: elasticsearch
    role: master
spec:
  selector:
    matchLabels:
      app: elasticsearch
      role: master
  serviceName: master-headless
  replicas: 3
  template:
    metadata:
      labels:
        app: elasticsearch
        role: master
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "role"
                operator: In
                values: 
                    - master
            topologyKey: "kubernetes.io/hostname"
      initContainers:
      - name: fix-the-volume-permission
        image: busybox
        command:
        - sh
        - -c
        - chown -R 1000:1000 /data
        securityContext:
          privileged: true
        volumeMounts:
        - name: storage
          mountPath: /data
      - name: init-sysctl
        image: busybox
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: es-master
        image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
        # resources:
        #   limits:
        #     cpu: "800m"
        #   requests:
        #     cpu: "500m"
        securityContext:
          privileged: true
        
        env:
        - name: node.master
          value: "true"
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        - name: ES_PATH_CONF
          value: "/usr/share/elasticsearch/config"
        ports:
        - containerPort: 9300
          name: internal
          
        volumeMounts:
        - name: storage
          mountPath: /data
        - name: config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
      volumes:
        - name: config
          configMap:
            name: master-config
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      storageClassName: "fast"
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 3Gi